# Generated by Django 5.2.8 on 2025-11-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.IntegerField()),
                ('id_voluntario', models.IntegerField()),
                ('id_inscrito', models.IntegerField()),
                ('hora_llegada', models.DateField()),
                ('hora_salida', models.DateField()),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
    ]
