# Generated by Django 5.2.8 on 2025-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_llegada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=200)),
                ('proposito', models.CharField(max_length=1000)),
                ('fecha_evento', models.DateField()),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id_inscrito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'inscritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_voluntario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150)),
                ('horas_acumuladas', models.IntegerField()),
            ],
            options={
                'db_table': 'voluntarios',
                'managed': False,
            },
        ),
    ]
